#定义contextPath，即项目根目录
server:
  context-path: /
spring:
  profiles:
    active: dev
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
#mybatis配置
mybatis:
#  type-aliases-package: com.yf.garden.bs.*
  mapper-locations: classpath:mapping/*.xml
  configuration:
    call-setters-on-nulls: true
#拦截URL
intercepturl: /garden/applet/api/**
swagger:
  title: 果园大屏后台api文档
  desc: 果园大屏后台api文档
#会话失效时间,单位天
session:
  timeout: 7
#短信验证码有效时间，单位分
sms:
  timeout: 21