server:
  port: 8090
spring:
  #数据源连接池默认使用的是Tomcat JDBC Connection Pool
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.71.187:3388/orchard_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: yfzn@123
    tomcat:
      min-idle: 3
      initial-size: 3
      max-active: 200
      max-idle: 20
      max-Wait: 60000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-open-prepared-statements: 20
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
  redis:
    host: 120.79.71.187
    port: 6385
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      max-wait: -1
    password: yfzn@123